services:

  codely.mooc_backend.controller.video.post:
    class: CodelyTv\MoocBackend\Controller\Video\VideoPostController
    parent: codely.mooc_backend.controller
    public: true

  codely.mooc_backend.controller.video.get:
    class: CodelyTv\MoocBackend\Controller\Video\VideoGetController
    parent: codely.mooc_backend.controller
    public: true

  codely.mooc_backend.controller.video.duration.path:
    class: CodelyTv\MoocBackend\Controller\Video\VideoDurationPatchController
    parent: codely.mooc_backend.controller
    public: true
