# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - Enhancement
  - Hacktoberfest
  - Bug
  - ⚡ To review
  - 😬 Reviewed
# Label to use when marking an issue as stale
staleLabel: Stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Issue automatically set as `Stale` after 30 days of inactivity.
  It will be closed in 7 days if we don't move it forward.
  We would like to maintain the repo as clean as possible.
  Thanks for your comprehension 👼
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Issue automatically closed due to being inactive during 7 days after flagging it as `Stale`.
  We would like to maintain the repo as clean as possible. Thanks for your comprehension 👼
