services:

  Doctrine\ORM\EntityManager:
    factory: [CodelyTv\Mooc\Shared\Infrastructure\Doctrine\MoocEntityManagerFactory, create]
    arguments:
      - driver:   '%mooc_database_driver%'
        host:     '%mooc_database_host%'
        port:     '%mooc_database_port%'
        dbname:   '%mooc_database_name%'
        user:     '%mooc_database_user%'
        password: '%mooc_database_password%'
      - '%codely.mooc.root_path%'
      - '%codely.mooc.infrastructure.database.on_demand%'
      - '%codely.mooc.infrastructure.database.schema_file%'
    tags:
      - { name: codely.mooc.database }
    public: true
