services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Mooc\:
    resource: '../../../../../../../*'

  # Notifications
  CodelyTv\Mooc\Notifications\Domain\Notifier: '@CodelyTv\Mooc\Notifications\Infrastructure\Notifier\SlackNotifier'

  CodelyTv\Mooc\Notifications\Infrastructure\Notifier\SlackNotifier:
    arguments:
      $hookUrl: '%slack_video_notification_hook_url%'
      $settings:
        - username: '%slack_video_notification_username%'
          channel: '%slack_video_notification_channel%'
