CodelyTv\Mooc\Students\Domain\Student:
  type: entity
  table: students

  id:
    id:
      type: student_id
      column: id
      length: 36

  embedded:
    name:
      class: CodelyTv\Mooc\Students\Domain\StudentName
      columnPrefix: false
    totalVideosCreated:
      class: CodelyTv\Mooc\Students\Domain\StudentTotalVideosCreated
      columnPrefix: false
