jms_serializer:

  visitors:
    json:
      options: JSON_PRETTY_PRINT


services:

  codely.mooc_backend.serializer.metadata.php_driver:
    class: CodelyTv\Shared\Infrastructure\Api\Serializer\ApiSerializerDriver

  jms_serializer.metadata_driver:
    alias: codely.mooc_backend.serializer.metadata.php_driver
    public: true


parameters:

  jms_serializer.infer_types_from_doctrine_metadata: false
  jms_serializer.datetime_handler.class: CodelyTv\Shared\Infrastructure\Api\Serializer\DateTimeHandler
