services:

  CodelyTv\Shared\Infrastructure\Bus\Command\SymfonySyncCommandBus:
    arguments: [!tagged codely.mooc.command]
    lazy: true

  CodelyTv\Shared\Infrastructure\Bus\Query\SymfonySyncQueryBus:
    arguments: [!tagged codely.mooc.query]
    lazy: true

  CodelyTv\Shared\Infrastructure\Bus\Event\SymfonySyncEventBus:
    arguments: [!tagged codely.mooc.subscriber]
    lazy: true
    public: true

  CodelyTv\Shared\Infrastructure\Bus\Event\SymfonySyncDomainEventPublisher:
    lazy: true
    public: true

  CodelyTv\Shared\Domain\Bus\Event\DomainEventPublisher: '@CodelyTv\Shared\Infrastructure\Bus\Event\SymfonySyncDomainEventPublisher'
  CodelyTv\Shared\Domain\Bus\Command\CommandBus: '@CodelyTv\Shared\Infrastructure\Bus\Command\SymfonySyncCommandBus'
  CodelyTv\Shared\Domain\Bus\Query\QueryBus: '@CodelyTv\Shared\Infrastructure\Bus\Query\SymfonySyncQueryBus'
